spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/cmp
    username: root 
    password:  
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
