trace: true
server:
  port: 5000
spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://taskoo-backbone.cmn4ebmkdtbo.ap-southeast-1.rds.amazonaws.com/taskoo_backbone
    username: taskoo_backbone
    password: taskoo_backbone

logging:
  level: 
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    
onboarding:
  url: 
  user.url: 

message.api:
  proxy:
    schme:
    hostname:
    port:
  connect.timeout: 
  read.timeout: 