spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taskoo_core
    username: root
    password:

logging:
  level: 
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    
es:
  base: http://localhost:8099/api/v1/es
  task:
    search: /tasks/search
    create: /tasks/create
    update: /tasks/update
    
  search.api: 
    proxy:
      scheme:
      hostname:
      port: 
    connect.timeout: 
    read.timeout: 
  
feedback:
  base: http://localhost:8081

  api:
    proxy: 
      scheme: 
      hostname: 
      port: 
    connect.timeout: 
    read.timeout: 